[tool.poetry]
name = "evaluation_function"
version = "0.0.1"
description = ""
authors = ["Andreas Pfurtscheller <andreas.pfurtscheller23@ic.ac.uk>"]
readme = "README.md"
packages = [{ include = "evaluation_function" }]

[tool.poetry.scripts]
evaluation_function = "evaluation_function.main:main"
evaluation_function_dev = "evaluation_function.dev:dev"

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.dependencies]
python = ">=3.11,<3.14"

# Uncomment below and comment out cpu if using macOS, the marker feature does not work (at least on my machine) - MM
torch = { version = "^2.9.0", markers = "sys_platform != 'linux'" }
#torch = { version = "^2.8.0+cpu", markers = "sys_platform == 'linux'", source = "pytorch-cpu" }

typing_extensions = "^4.15.0"
lf_toolkit = { git = "https://github.com/lambda-feedback/toolkit-python.git", branch = "main", extras = [
    "ipc",
] }
numpy = "^2.3.4"
lmdb = "^1.7.5"

[tool.poetry.group.overrides.dependencies]
# Override sympy because lf-toolkit pins sympy==1.12, 
# but torch>=2.8.0 requires sympy>=1.13.3.
# Remove this once lf-toolkit updates its dependency:
# https://github.com/lambda-feedback/toolkit-python/issues/2
sympy = ">=1.14.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
flake8 = "^7.3.0"
nltk = "^3.9.2"
matplotlib = "^3.10.7"
pandas = "^2.3.3"
sentencepiece = "^0.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
